services:
  configuration-server:
    build:
      context: ./services/configuration
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    restart: always
    depends_on:
      - configuration_db
    links:
      - configuration_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://configuration_db:5432/configuration?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - monitoring-tools-network
  configuration_db:
    container_name: postgres_configuration_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: configuration
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - monitoring-tools-network
  analytics_db:
    container_name: postgres_analytics_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - monitoring-tools-network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  monitoring-tools-network:
