server:
  port: 8072

spring:
  application:
    name: monitoring-tools-monitor
  threads:
    virtual:
      enabled: true

client:
  url:
    configuration-server: http://localhost:8070/api/v1
    analytics-server: http://localhost:8071/api/v1

application:
  max-configurations: 5
