services:
  configuration_db:
    container_name: postgres_configuration_container_dev
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: configuration
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container_dev
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

# Volumes
volumes:
  db-data:
